openapi: 3.1.0
info:
  version: 1.0.0
  title: idosell-clone app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of idosell-clone app
tags:
  - name: Products
    description: Operations about Products.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://idosell-clone.onrender.com
paths:
  /products:
    get:
      tags:
        - Products
      summary: Get all products
      operationId: getAllProducts
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/products/get.yaml
    post:
      tags:
        - Products
      summary: Create a new product
      operationId: createProduct
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/products/post.yaml
  /products/{id}:
    get:
      tags:
        - Products
      summary: Get a product by ID
      operationId: getProductById
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/products/{id}/get.yaml
    put:
      tags:
        - Products
      summary: Update a product by ID
      operationId: updateProductById
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/products/{id}/put.yaml
    delete:
      tags:
        - Products
      summary: Delete a product by ID
      operationId: deleteProductById
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/products/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: Unauthorized access. Token might be missing or invalid.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Unauthorized'
    Forbidden:
      description: Forbidden. Token lacks necessary permissions.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Forbidden'
